baseURL = "https://cciobanu.dev/"
languageCode = "en-us"
title = "cciobanu"
theme = "hugo-coder"

[params]
  author = "cciobanu"
  description = "A blog about programming, and tech"
  keywords = ["selfhosting", "programming", "technology"]
  avatarURL = "images/avatar.jpg"
  dateFormat = "January 2, 2006"

[[menu.main]]
  name = "Articles"
  url = "/articles/"
  weight = 1
